import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
const require = createRequire('c:/Users/telmat/Desktop/hackaton-app/package.json');
const { chromium } = require('@playwright/test');
process.chdir('c:/Users/telmat/Desktop/subitis-landing');
const srv = createServer(async (_q, r) => { r.writeHead(200,{'Content-Type':'text/html; charset=utf-8'}); r.end(await readFile('index.html')); });
await new Promise(r => srv.listen(4193, r));
const nav = await chromium.launch();
const p = await (await nav.newContext({ viewport: { width: 390, height: 844 } })).newPage();
await p.goto('http://localhost:4193/', { waitUntil: 'load' });
await p.evaluate(() => document.fonts.ready);
const lire = async () => p.evaluate(() => document.querySelector('.barre').classList.contains('repliee'));
console.log('  haut de page        : repliee =', await lire());
await p.mouse.wheel(0, 900); await p.waitForTimeout(400);
console.log('  apres descente      : repliee =', await lire());
await p.mouse.wheel(0, 900); await p.waitForTimeout(400);
console.log('  descente continue   : repliee =', await lire());
await p.mouse.wheel(0, -300); await p.waitForTimeout(400);
console.log('  remontee            : repliee =', await lire());
await nav.close(); srv.close();
